name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Truffle - compile
      run: npx truffle compile
    - name: Truffle - test
      run: npx truffle test --stacktrace
    - name: Frontend - Clean and build
      run: npm run build
    - name: Frontend - Tests
      run: npm test
    - name: Package frontend artifacts for deployment
      uses: actions/upload-artifact@v2
      with:
        name: frontend-artifacts
        path: |
          dist

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: deployed
    - name: Unpack frontend artifacts
      uses: actions/download-artifact@v2
      with:
        name: frontend-artifacts
        path: dist
    - name: remove old deployment (kepp CNAME file)
      run: |
        ls -l docs
        find docs/ ! -name 'CNAME' -type f -exec rm -rf {} +
        ls -l docs
    - name: copy new deployment
      run: |
        ls -l dist
        cp -r dist/* docs/
        ls -l docs
    - name: commit and push deployment
      run: |
        git config user.name createz-github-actions
        git config user.email github-actions@createz.xyz
        git add docs
        git diff-index --quiet HEAD || git commit -m "Deploy build $GITHUB_SHA"
        git push
